language: go
notifications:
  email:
    recipients:
    - lists@dhrapson.com
install:
- go get github.com/mitchellh/gox
- go get -d -v -t ./...
script:
- go install -v ./...
- go test -v ./...
- "[ `gofmt -l *.go | wc -l` = 0 ]"
after_success:
- '[ "${TRAVIS_TAG}" != "" ] && gox -ldflags "-X github.com/dhrapson/sched-load/cmd.Version=`git
  describe --tags` -X github.com/dhrapson/sched-load/cmd.BuildTime=`TZ=UTC date -u
  ''+%Y-%m-%dT%H:%M:%SZ''` -X github.com/dhrapson/sched-load/cmd.GitHash=`git rev-parse
  HEAD`" -output "dist/{{.Dir}}-{{.OS}}-{{.Arch}}"'
deploy:
  provider: releases
  file_glob: true
  api_key: "$GITHUB_TOKEN"
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: pwvu+Tp/p4Jt461nvhT3ibwr05csFCTH44zAPSbToODP9hZNn0R9m4u0WVrWtPWuZRSnNDCWRel2E0MaaXCaS9Xa+LtzGDkSPw1+h/iPz6r9f+XGtjpT7Bydv83b6rcdytRtfDnymXAadRM92tbnPiJjuxpBs5NTZhmt+SOOQdmrz1Eh9viWIOtqHfRTQmTdN1iTCaO1UnBAeZNP33wmBv9FA0QfVs9uZQeQd/4vpFUsmCJvp92ux1lQc2UFz7gKIqoB644hc4Ni6lxbAP+ZBV/+tAx7XOvIuqMYiru3HgL+HdutvE1OUgnH9yxyOOs64hB0R6OfPPrtX0GSfPNk/PX+PeWLI8AZmzp/njYJtvkrj3M5+dI91doNwXZw8dRHStmoZvTLe92f3NdgWJWWUhf7DHJxF/x3clLRLEU1z+CPoSCPpg1699jaO9/0T6hPopgA8RqcfV3cPon68TI0dsWRepUPRAGMBRIdtkoEIXh/Xr+HxCEHDqw9855dTZomPsqrU1PiexyUpa3vyW2KNugqWayECvifUnc0b/1qH71Tud194mREiy4wC74zE/wpvG/OUlaxj7unkigladW+bPbtvFkpam5gYRhNGrfP39HyVGyEouSglokfR8MhFGOs7Kt+pGkYxaEc0dz+2QZS9VO7ECrL2SYbzSpcHQTmZZA=
  - secure: Eegom7KonbsOHLSgX6EPbrvP74ZBlOMpKA4vhxDFnJOQnPGwarTAPmysL1+Ot0mkODdKLzSlaIHe+oKHNUpPX26EUI5DFzrrtyzgQTJNpyZY6vA9+WR7Ase/7MKjkMmfnDTw9S/GNmxyNJhcC3iyZmeOEStfrzXSGUz0ZixDRJa/gM6SitGxyOGzTH0vrMiKWnzx26gofLWjDLldfOyv+e7sHKtqig6W6MKFpnUY+/jYT2xeYQu/Ki4kAjgOG2BBH0wW/xOi7tu4flPRpYtK3dwyLaTc/lWl30AkNkgcNFtRpnDJMda3+z1cNI8eN6OnciHlhF025S1bDmd8aik+YMgTIwx6Ayb4CR19Za/ZkBDA7G5wRsRHsp09S9+kPAzxj5ezElHgyC3qF1PWla3LdJtmXR3q8mU++DVO2wa1TXDaR/Z6+y8IvTfMVJdSFIcD9RBQ6OAr4ClZHfrc9GT1qMFHkorQkhBKZ5VJ9+bATzOBdn42WmzBJctXX7HG1n4+I9R0RCmhl7+tNOs4IKYq6Yho6NKkFnQkfP2tcfcfExfaWzRa44sF7PLAUSufrCslZ2YtMulcJiJetDPSo4usXd8Eb26rmP4SKrfOtlCjHUWYULb1SCS7OHsMeLL/aZlT40GHdPOsI0yX4DSENZu7atyQYWah4DnplqjE5CT1tBA=
