language: go
notifications:
  email:
    recipients:
    - lists@dhrapson.com
install:
- go get github.com/mitchellh/gox
- go get -d -v -t ./...
script:
- go install -v ./...
- go test -v ./...
- "[ `gofmt -l *.go | wc -l` = 0 ]"
after_success:
- '[ "${TRAVIS_TAG}" != "" ] && gox -ldflags "-X github.com/dhrapson/sched-load/cmd.Version=`git
  describe --tags` -X github.com/dhrapson/sched-load/cmd.BuildTime=`TZ=UTC date -u
  ''+%Y-%m-%dT%H:%M:%SZ''` -X github.com/dhrapson/sched-load/cmd.GitHash=`git rev-parse
  HEAD`" -output "dist/{{.Dir}}-{{.OS}}-{{.Arch}}"'
deploy:
  provider: releases
  file_glob: true
  api_key: "$GITHUB_TOKEN"
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: nz92YSWuLbYEGY1VfQgHrmjA02OtdPiD8xQRJBEVWc81KfhE6V4jzVR506BdG+vq4bUXivvmwhvXkMxah7Z75JZhC6uGeubWNN9/9Mcoe/LegjByQe/8TJXbvEuANxleKVZHgq7RZ2t+zBmDVjL9xaVeSrIBzXrOwWBzhB+RkH8N2fKaabJkPfrABClXThAHgHH+BWMy9atBemHdydxM5Q1EzFpcwwe/2xUrSFgIS+zLDX1z7+BhC6Cvl/cXyYYMeW4cAT3njkTULhf4GSwXOe9avxvTc7g56dojtOl0he7mC6rSitZFj546rVUqWncRGI/fvyAPcpqN6bPKUg64RcxFwZinp3ttKGGDUIYUdUZYJVAWpIf98I95ZQbpPm0oH5KnYtC+iXo/34ugKm5XOVoO7eB+GPRrxP79h9meAOzv3KplkJrsZ4bmzSCST1NH5gRZBJv6KqX95F4YIR72arCqkO+5UuB8/gq5X2txVHLYXZF2n2SIIzyM5T1AO21h5T9LYiTOnrYm/kFrYSU3B6MKUaBbtuDJcs00nLRrvp1AjIR92xBpuvL0MpjaTaKbOcyokkOBRFujYiBvXnVxYlqwDZA+6kCPuNcx27tpBSqgPlIV/Ags07UwszpjMFsigsdzjeMInLUVhaUsG+4XKZ6PJE9bQ0Sd2OjcoetUUqo=
  - secure: a4XDkCpFwmiYvOx+TzdiAXEjRQeod234w42OghG2aA9PK/KI9cUaBmHohkdeJfjvZR+ZO6V04qCNelo7y2WrdIAkrlvYod6+CTlz4sQeNdS64IxCIzRWYtvgFyIGj4sQk+xv4He3eZG6/5QSpchizyhlAL285Ycgr2gV8ZpHa6kfMAiNixmGR/ziEYpx50Ae082/xPMLngHN+cg731ZjjBtQBxfJAJpI5kWY7UyLZKGTYXP5VLbwVH+vvc1USgLw7Uku5h+dct0WRVoQLLvfBRFrvjKQ5zSpggnm+3r82iDySavzXlzUA/iKG3irjpLDstEqtOWzCNuYkF92h/ddwZ1yttYOIoTQYI1VeVPTr7c5SUAcL4qzT6iNaptnXiuw0ni0r3222Uj0+KbC/pUOLG1ApEs/7OStUIV5fPiD6XptLE1BtCUo9OkLTiTE6+NIMFqQhpkzIvo2gTCcSSpE2XB9dClX5gQBrcUAWGGpwecnqqWLTzCM3z5nUq18/QWpWf5SegTLCq335vCizHKCnHOcGrCPMyQYOyFjGpDO1jFcDyTiW5onGzf/TEj7g9wxOxW4Y30HdxixGceiAv+6oie1Ulc7RMfK5dUjCPYAp0M9lP5YG14L/LK8c7c0HF0zGx9OJ7u1eltVmVVYz3vYzMKpNBhfe8lB4IPFXz7frZ0=
