language: go

notifications:
  email:
    recipients:
      - lists@dhrapson.com

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64

before_install:
  - curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/v1.0.0/gimme
  - chmod +x ~/bin/gimme
  
install:
  - go get -d -v ./...

script:
  - go build -v ./...
