language: go

notifications:
  email:
    recipients:
      - lists@dhrapson.com

install:
  - go get github.com/mitchellh/gox
  - go get -d -v -t ./...

script:
  - go test -v ./...
  - "[ `gofmt -l *.go | wc -l` = 0 ]"

after_success:
  - |-
    [ "${TRAVIS_TAG}" != "" ] && [ "${TRAVIS_GO_VERSION}" == "1.7" ] && gox -ldflags "-X github.com/dhrapson/sched-load/cmd.Version=`git describe --tags` -X github.com/dhrapson/sched-load/cmd.BuildTime=`TZ=UTC date -u '+%Y-%m-%dT%H:%M:%SZ'` -X github.com/dhrapson/sched-load/cmd.GitHash=`git rev-parse HEAD`" -output "dist/{{.Dir}}-{{.OS}}-{{.Arch}}"

deploy:
  provider: releases
  file_glob: true
  api_key: "$GITHUB_TOKEN"
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true
    go: 1.7
